services:
  deploy-contracts:
    build: ./contract-deployer
    environment:
      - ANVIL_RPC=http://anvil:8545

  mock-paymaster:
    build: ./mock-paymaster
    environment:
      - ALTO_RPC=http://alto:4337
      - ANVIL_RPC=http://anvil:8545

  anvil:
    image: ghcr.io/foundry-rs/foundry:nightly-f6208d8db68f9acbe4ff8cd76958309efb61ea0b
    ports: [ "8545:8545" ]
    entrypoint: [ "anvil", "--host", "0.0.0.0" ]

  alto:
    image: ghcr.io/pimlicolabs/alto/tmp:main-501c912-1712399621
    ports: [ "4337:4337" ]
    depends_on:
      deploy-contracts:
        condition: service_completed_successfully
    environment:
      ALTO_NETWORK_NAME: "local"
      ALTO_ENTRY_POINTS: "0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789,0x0000000071727De22E5E9d8BAf0edAc6f37da032"
      ALTO_ENTRY_POINT_SIMULATIONS_ADDRESS: "0xb5b2391Af1Ec0D8694c8543E2EDe2Ce9a031a10D"
      ALTO_ENTRY_POINT_VERSION: "0.7"
      ALTO_API_VERSION: "v2"
      ALTO_RPC_URL: "http://anvil:8545"
      ALTO_MIN_BALANCE: "0"
      ALTO_UTILITY_PRIVATE_KEY: "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
      ALTO_SIGNER_PRIVATE_KEYS: "0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d"
      ALTO_RPC_MAX_BLOCK_RANGE: 10000
      ALTO_PORT: 4337

  test-cases:
    build: ./test-cases
    environment:
      - PAYMASTER_RPC=http://mock-paymaster:8545
      - ALTO_RPC=http://alto:8545
      - ANVIL_RPC=http://anvil:8545
    volumes:
      - ../packages/permissionless/:/app/permissionless
